overwin/urls.py
from django.urls import path
from .views.mypage import MyPageView
from .views.account_register_and_login import AccountRegisterView, LoginView, LogoutView
from .views.game_player_info_and_stats import GamePlayerInfoView
from .views.search_game_player import GamePlayerSearchView
from .views.favorite_game_player import FavoritePlayerView
from .views.account_info import AccountInfoView,UpdateAccountInfoView,DeleteAccountInfoView
from .views.party_recruitment import RecruitmentListView,PartyRecruitmentCreateView,PartyRecruitmentDetailView,PartyRecruitmentDeleteView, PartyRecruitmentUpdateView


app_name = "overwin"
urlpatterns = [
    #mypage関連
    path('mypage/',               MyPageView.as_view(),               name='mypage'),
    #accountのログイン、登録関連
    path('account-register/',     AccountRegisterView.as_view(),      name='account_register'),
    path('',                      LoginView.as_view(),                name='login'),
    path('logout/',               LogoutView.as_view(),               name='logout'),
    #個人戦績
    path('game-player-info/',     GamePlayerInfoView.as_view(),       name='game_player_info'),
    #プレイヤー検索
    path('search-game-player/',   GamePlayerSearchView.as_view(),     name='search_game_player'),
    #お気に入りプレイヤー表示
    path('favorite-game-player/', FavoritePlayerView.as_view(),       name='favorite_game_player'),
    #アカウント情報関連
    path('account-info/',         AccountInfoView.as_view(),                  name='account_info'),
    path('account-info/update/',  UpdateAccountInfoView.as_view(),                name='account_info_update'),
    path('account-info/delete/',        DeleteAccountInfoView.as_view(),                     name='account_delete'),
    #パーティー募集
    path('party-recruitment/',            RecruitmentListView.as_view(),        name='party_recruitment_list'),
    path('party-recruitment/create/',          PartyRecruitmentCreateView.as_view(), name='party_recruitment_create'),
    path('party-recruitment/<int:pk>/delete/', PartyRecruitmentDeleteView.as_view(), name='party_recruitment_delete'),
    path('party-recruitment/<int:pk>/detail/', PartyRecruitmentDetailView.as_view(), name='party_recruitment_detail'),
    path('party-recruitment/<int:pk>/update/', PartyRecruitmentUpdateView.as_view(), name='party_recruitment_update'),
]

road_map_products/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path("", include("overwin.urls")),
    path('admin/', admin.site.urls),
]

overwin/forms/account_register_and_login.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from ..models import User
from ..forms_utils import CustomForm

class UserRegisterForm(CustomForm, UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')

class LoginForm(CustomForm, AuthenticationForm):
    class Meta:
        model = User

class AccountInfoUpdateForm(CustomForm, UserChangeForm):
    #TODO パスワードの変更処理
    password = None
    class Meta:
        model = User
        fields = ('username', 'email')

overwin/forms/party_recruitment.py
from django import forms
from ..forms_utils import CustomForm
from ..models import Recruitment

class RecruitmentForm(CustomForm, forms.ModelForm):
    class Meta:
        model = Recruitment
        fields = ['max_recruit_member', 'comment']

overwin/views/account_info.py
from ..models import User
from ..forms.account_register_and_login import AccountInfoUpdateForm
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from django.utils.decorators import method_decorator

@method_decorator(login_required, name="dispatch")
class AccountInfoView(generic.TemplateView):
    template_name = 'overwin/account_info/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        context['email'] = self.request.user.email
        return context

@method_decorator(login_required, name="dispatch")
class UpdateAccountInfoView(generic.UpdateView):
    template_name = 'overwin/account_info/update.html'
    model = User
    success_url = reverse_lazy('overwin:account_info')
    form_class = AccountInfoUpdateForm

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.pk)

    def get(self, request):
        self.object = self.get_object()
        form = self.get_form()
        context = self.get_context_data(form=form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            form.save()
            return redirect(self.get_success_url())
        else:
            return self.form_invalid(form)

@method_decorator(login_required, name="dispatch")
class DeleteAccountInfoView(generic.DeleteView):
    model = User
    success_url = reverse_lazy('overwin:login')
    template_name = 'overwin/account_info/delete.html'

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.pk)

overwin/views/account_register_and_login.py
from django.contrib.auth import authenticate
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from django.views import generic
from django.urls import reverse_lazy
# NOTE: ..formsではなくformsの場合、no module named'forms'エラーが出る
from ..forms.account_register_and_login import UserRegisterForm,LoginForm

class AccountRegisterView(generic.CreateView):
    form_class = UserRegisterForm
    template_name = "overwin/account_register_and_login/register.html"
    success_url = reverse_lazy("overwin:login")

    def form_valid(self, form):
        response = super().form_valid(form)
        password = form.cleaned_data.get("password")
        username = form.cleaned_data.get("username")
        user = authenticate(username=username, password=password)
        return response

class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = "overwin/account_register_and_login/login.html"

class LogoutView(BaseLogoutView):
    success_url = reverse_lazy('overwin:login')

overwin/views/favorite_game_player.py
from django.views import generic
from ..models import FavoriteGamePlayer
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import redirect

@method_decorator(login_required, name="dispatch")
class FavoritePlayerView(generic.ListView):
    template_name = "overwin/favorite_game_player/index.html"
    model = FavoriteGamePlayer

    def get_queryset(self):
        return FavoriteGamePlayer.objects.filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        favorite_id = request.POST.get('favorite_id')
        if favorite_id:
            favorite = FavoriteGamePlayer.objects.get(id=favorite_id, user=request.user)
            favorite.delete()
        return redirect('overwin:favorite_game_player')

overwin/views/game_player_info_and_stats.py
from django.views import generic
from ..models import GamePlayer
from ..utils import fetch_data_from_api, rate_calculation, seconds_to_hour_and_minutes, format_num

class GamePlayerInfoView(generic.TemplateView):
    template_name = 'overwin/game_player_info_and_stats/game_player_info.html'

    def fetch_player_info_by_battle_tag(self):
        battle_tag = self.request.GET.get('battle_tag')
        battle_tag_to_fetch = battle_tag.replace("#","-")

        try:
            #推薦レベル、ランク、アイコン、バナー、称号
            fetch_player_info_summary = fetch_data_from_api(f"players/{battle_tag_to_fetch}/summary", params=None)

            player_info ={
                'avatar':           fetch_player_info_summary['avatar'],
                'namecard':         fetch_player_info_summary['namecard'],
                'title':            fetch_player_info_summary['title'],
                'endorsement':      fetch_player_info_summary['endorsement'],
                'tank_rank_cs' :    fetch_player_info_summary['competitive']['console']['tank'],
                'damage_rank_cs' :  fetch_player_info_summary['competitive']['console']['damage'],
                'support_rank_cs' : fetch_player_info_summary['competitive']['console']['support'],
            }

        # todo: APIエラーになったときの処理
        except Exception:
            pass
        # todo: 200じゃなかったときの処理
        # if response.status_code != 200:
        #     pass
        return player_info

    def fetch_player_hero_info_by_battle_tag(self):
        battle_tag = self.request.GET.get('battle_tag')
        battle_tag_to_fetch = battle_tag.replace("#","-")

        try:
            #ヒーローごとの簡単なスタッツを取得
            fetch_hero_stats_summary = fetch_data_from_api(f"players/{battle_tag_to_fetch}/stats/summary", params={'gamemode':'competitive'})

            heroes_stats_summary_dict = fetch_hero_stats_summary["heroes"]
            #TODO:ヒーローの画像も入れる

            player_hero_info = {}

            for hero_name, hero_stats in heroes_stats_summary_dict.items():
                time_played = seconds_to_hour_and_minutes(hero_stats["time_played"])
                win_rate = format_num(hero_stats["winrate"],2)

                kill_count = hero_stats["average"].get("eliminations", 0)
                death_count = hero_stats["average"].get("deaths", 0)
                kill_count_divide_death_count = rate_calculation(kill_count,death_count,2)

                average_damage = int(hero_stats["average"].get("damage", 0))

                player_hero_info[hero_name] = {
                    "time_played" :                   time_played,
                    "win_rate" :                      win_rate,
                    "kill_count_divide_death_count" : kill_count_divide_death_count,
                    "average_damage" :                average_damage,
                }

        # todo: APIエラーになったときの処理
        except Exception:
            pass
        # todo: 200じゃなかったときの処理
        # if response.status_code != 200:
        #     pass
        return player_hero_info

    def get_context_data(self, **kwargs):
        #親のget_context_dataを呼び出している。基本的なコンテキストデータが入っている
        context = super().get_context_data(**kwargs)
        battle_tag = self.request.GET.get('battle_tag')
        if battle_tag:
            player = GamePlayer.objects.filter(battle_tag=battle_tag).first()
            context['player'] = player
            context['player_info'] = self.fetch_player_info_by_battle_tag()
            context['player_hero_info'] = self.fetch_player_hero_info_by_battle_tag()
        return context

overwin/views/game_player_stats.py
from ..models import *
from ..forms import *
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views import generic

class GamePlayerInfoView(generic.TemplateView):
    template_name = 'overwin/player_stats.html'
# todo:コンテキストの処理とAPIから取得する関数を別にする
    def get_context_data(self, **kwargs):
        #親のget_context_dataを呼び出している。基本的なコンテキストデータが入っている
        context = super().get_context_data(**kwargs)
        battle_tag = self.request.GET.get('battle_tag')
        if battle_tag:
            player = GamePlayer.objects.filter(battle_tag=battle_tag).first()
            context['player'] = player
        return context

overwin/views/mypage.py
from django.views import generic

class MyPageView(generic.TemplateView):
    template_name = "overwin/mypage/index.html"

overwin/views/party_recruitment.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy,reverse
from django.shortcuts import render, get_object_or_404,redirect
from ..models import Recruitment, JoinMember
from ..forms.party_recruitment import RecruitmentForm

@method_decorator(login_required, name="dispatch")
class RecruitmentListView(generic.ListView):
    model = Recruitment
    template_name = 'overwin/party_recruitment/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_recruitment']   = Recruitment.objects.filter(owner=self.request.user)
        context['other_recruitments'] = Recruitment.objects.exclude(owner=self.request.user)
        return context

@method_decorator(login_required, name="dispatch")
class PartyRecruitmentCreateView(generic.CreateView):
    template_name = "overwin/party_recruitment/create.html"
    model = Recruitment
    form_class = RecruitmentForm
    success_url = reverse_lazy("overwin:party_recruitment_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

@method_decorator(login_required, name="dispatch")
class PartyRecruitmentDetailView(generic.DetailView):

    def get(self, request, pk):
        recruitment = get_object_or_404(Recruitment, pk=pk)
        is_owner = request.user.pk == recruitment.owner.pk
        applicated_to_recruiting = JoinMember.objects.filter(recruitment=recruitment, join_member=request.user).exists()
        possible_to_entry = recruitment.possible_to_entry
        form = RecruitmentForm(instance=recruitment)
        approved_message = None

        if is_owner:
            joined_members = JoinMember.objects.filter(recruitment=recruitment, is_approved=True)
            applicant_members = JoinMember.objects.filter(recruitment=recruitment, is_approved=False)
        else:
            joined_members = JoinMember.objects.filter(recruitment=recruitment, is_approved=True)
            applicant_members = None
            try:
                joined_member = JoinMember.objects.get(recruitment=recruitment, join_member=request.user, is_approved=True)
                approved_message = joined_member.message
            except JoinMember.DoesNotExist:
                pass

        context = {
            'recruitment': recruitment,
            'is_owner': is_owner,
            'applicated_to_recruiting' : applicated_to_recruiting,
            'possible_to_entry' : possible_to_entry,
            'form' : form,
            'joined_members': joined_members,
            'applicant_members': applicant_members,
            'approved_message': approved_message,
        }
        return render(request, 'overwin/party_recruitment/detail.html', context)

    def post(self, request, pk):
        recruitment = get_object_or_404(Recruitment, pk=pk)
        is_owner = request.user.pk == recruitment.owner.pk
        form = RecruitmentForm(instance=recruitment)

        # 募集者側の操作
        ## 参加申請の許可
        if 'approve_member' in request.POST:
            #NOTE: 許可ボタンが押された時に、そのユーザーのIDを取得
            member_id = request.POST.get('member_id')
            message = request.POST.get('message')
            if member_id and message:
                try:
                    join_member = JoinMember.objects.get(recruitment=recruitment, join_member__id=member_id, is_approved=False)
                    join_member.is_approved = True
                    join_member.message = message
                    join_member.save()
                    recruitment.current_member_count += 1
                    recruitment.save()
                except JoinMember.DoesNotExist:
                    pass
            return redirect('overwin:party_recruitment_detail', pk=pk)

        # 参加者側の操作
        if 'join' in request.POST:
            # 未申請の場合は参加申請ができる
            if not JoinMember.objects.filter(recruitment=recruitment, join_member=request.user).exists():
                JoinMember.objects.create(recruitment=recruitment, join_member=request.user)
                return redirect('overwin:party_recruitment_detail', pk=pk)

        context = {
            'recruitment': recruitment,
            'is_owner': is_owner,
            'form' : form
        }
        return render(request, 'overwin/party_recruitment/detail.html', context)

@method_decorator(login_required, name="dispatch")
class PartyRecruitmentUpdateView(generic.UpdateView):
    template_name = 'overwin/party_recruitment/update.html'
    model = Recruitment
    form_class = RecruitmentForm

    def get_success_url(self):
        return reverse("overwin:party_recruitment_detail", kwargs={'pk': self.object.pk})

@method_decorator(login_required, name="dispatch")
class PartyRecruitmentDeleteView(generic.DeleteView):
    model = Recruitment
    success_url = reverse_lazy('overwin:party_recruitment_list')
    template_name = 'overwin/party_recruitment/delete.html'

overwin/templates/overwin/party_recruitment/create.html
{% extends 'overwin/base.html'%}
{% load static %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'overwin/css/party_recruitment/create.css'%}">
{% endblock %}

{% block content %}
<div class="content">
    <h1>募集新規作成</h1>
    <form method="post">
        <div class="field-area">
        {% csrf_token %}
        {{ form.as_p }}
        </div>
        <div class="action-button-area">
            <button type="submit" class="btn-primary">作成</button>
        </div>
    </form>
</div>
{% endblock %}

overwin/templates/overwin/party_recruitment/delete.html
{% extends 'overwin/base.html'%}
{% load static %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'overwin/css/party_recruitment/delete.css'%}">
{% endblock %}

{% block content %}
<div class="content">
    <form method="POST">
        {% csrf_token %}
        <p class="error-message">募集を削除しますか？</p>
        <div class="btn-area"><button type="submit" class="btn btn-primary btn-success" >削除</button></div>
        <div class="back-link-area"><a href="{% url 'overwin:party_recruitment_detail' pk=recruitment.pk %}" class="btn btn-secondary back-link">募集詳細に戻る</a></div>
    </form>
</div>
{% endblock %}

overwin/templates/overwin/party_recruitment/detail.html
{% extends 'overwin/base.html'%}

{% load static %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'overwin/css/party_recruitment/detail.css'%}">
{% endblock %}

{% block content %}
<div class="content">
    <h2>募集詳細</h2>
    <!-- 募集者の詳細画面 -->
    {% if is_owner %}
    <div class="card">
        <div class="card-recruiter-area">
            <h2>募集者：{{ recruitment.owner.username }}</h2>
            <a href="{% url 'overwin:party_recruitment_update' recruitment.id %}" class="update-link">募集編集ページへ</a>
        </div>
        <div class="member-num-area">
            <h4>募集人数</h4>
            <p>{{ recruitment.max_recruit_member }}人</p>
            <h4>現在の参加人数</h4>
            <p>{{ recruitment.current_member_count }}人</p>
        </div>
        <h4>参加者一覧</h4>
        {% if joined_members %}
            <ul>
            {% for member in joined_members %}
                <li>{{ member.join_member.username }}</li>
            {% endfor %}
            </ul>
        {% else %}
            <p>参加者はいません。</p>
        {% endif %}
        <h4>参加申請者一覧</h4>
        {% if applicant_members %}
            <ul>
            {% for member in applicant_members %}
                <div class="applicant-area">
                    <li>{{ member.join_member.username }}</li>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="member_id" value="{{ member.join_member.id }}">
                        <input type="text" name="message" maxlength="20" placeholder="（例）Player#1234" required>
                        <button type="submit" name="approve_member" class="btn-primary apply-btn">バトルタグと参加許可を送信</button>
                    </form>
                </div>
            {% endfor %}
            </ul>
        {% else %}
            <p>参加申請者はいません。</p>
        {% endif %}
        <h4>コメント</h4>
        <p>{{ recruitment.comment }}</p>
    </div>
    <!-- 参加者の募集詳細画面 -->
    {% else %}
    <div class="card">
        {% if applicated_to_recruiting %}
            <p class="status-message">参加申請済み</p>
        {% elif not possible_to_entry %}
            <p class="status-message">満員です</p>
        {% endif %}
        {% if approved_message %}
            <p class="applyed-message">参加が許可されました！ 募集者のバトルタグ: {{ approved_message }}</p>
        {% endif %}
        <div class="card-recruiter-area">
            <h2>募集者：{{ recruitment.owner.username }}</h2>
        </div>
        <div class="member-num-area">
            <h4>募集人数</h4>
            <p>{{ recruitment.max_recruit_member }}人</p>
            <h4>現在の参加人数</h4>
            <p>{{ recruitment.current_member_count }}人</p>
        </div>
        <h4>参加者一覧</h4>
        {% if joined_members %}
            <ul>
            {% for member in joined_members %}
                <li>{{ member.join_member.username }}</li>
            {% endfor %}
            </ul>
        {% else %}
            <p>参加者はいません。</p>
        {% endif %}
        <h4>コメント</h4>
        <p>{{ recruitment.comment }}</p>
    </div>
    {% if not applicated_to_recruiting and possible_to_entry %}
    <form method="post">
        {% csrf_token %}
        <div class="submit-btn-area"><button type="submit" name="join" class="btn entry-btn btn-primary">参加申請</button></div>
    </form>
    {% endif %}
{% endif %}
<div class="list-link-area"><a href="{% url 'overwin:party_recruitment_list'%}" class="list-link">募集一覧に戻る</a></div>
</div>
{% endblock %}

overwin/templates/overwin/party_recruitment/index.html
{% extends 'overwin/base.html'%}
{% load static %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'overwin/css/party_recruitment/index.css'%}">
{% endblock %}

{% block content %}
<div class="content">

<div class="title-and-link-area">
    <h2 class="title">自分の募集</h2>
    <a class="create-link btn-secondary" href="{% url 'overwin:party_recruitment_create'%}">募集の新規作成</a>
</div>

<div class="card-container">
    {% for recruitment in user_recruitment %}
    <div class="card">
        <a href="{%url 'overwin:party_recruitment_detail' recruitment.id %}">
        <div class="card-content">
            <h3 class="recruiter">募集者：{{ recruitment.owner.username }}</h3>
            <div class="details">
                <div class="member-num">
                    <h4 class="participants">参加人数: {{ recruitment.current_member_count }}</h4>
                    <h4 class="max-recruit-member">募集人数: {{ recruitment.max_recruit_member }}</h4>
                </div>
                {% if recruitment.comment %}
                <p class="comment"> {{ recruitment.comment }}</p>
                {% else %}
                <p class="comment"> - </p>
                {% endif %}
            </div>
        </div>
        </a>
    </div>

    {% empty %}
    <p class="no-recruitment-message">募集を作成していません</p>
    {% endfor %}
</div>

<h2 class="title recruitment-list">募集一覧</h2>
<div class="card-container">
    {% for recruitment in other_recruitments %}
    <div class="card">
        <a href="{%url 'overwin:party_recruitment_detail' recruitment.id %}">
        <div class="card-content">
            <h3 class="recruiter">募集者：{{ recruitment.owner.username }}</h3>
            <div class="details">
                <div class="member-num">
                    <h4 class="participants">参加人数: {{ recruitment.current_member_count }}</h4>
                    <h4 class="max-recruit-member">募集人数: {{ recruitment.max_recruit_member }}</h4>
                </div>
                {% if recruitment.comment %}
                <p class="comment"> {{ recruitment.comment }}</p>
                {% else %}
                <p class="comment"> - </p>
                {% endif %}
            </div>
        </div>
        </a>
    </div>
    {% empty %}
    <p class="no-recruitment-message">募集が作成されていません</p>
    {% endfor %}
</div>
{% endblock %}

overwin/templates/overwin/party_recruitment/party_recruitment_delete.html
{% extends 'overwin/base.html'%}
{% load static %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'overwin/css/party_recruitment/party_recruitment_delete.css'%}">
{% endblock %}

{% block content %}
<div class="content">
    <form method="POST">
        {% csrf_token %}
        <p class="error-message">募集を削除しますか？</p>
        <div class="btn-area"><button type="submit" class="btn btn-primary btn-success" >削除</button></div>
        <div class="back-link-area"><a href="{% url 'overwin:party_recruitment_detail' pk=recruitment.pk %}" class="btn btn-secondary back-link">募集詳細に戻る</a></div>
    </form>
</div>
{% endblock %}

overwin/templates/overwin/party_recruitment/update.html
{% extends 'overwin/base.html'%}
{% load static %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'overwin/css/party_recruitment/update.css'%}">
{% endblock %}

{% block content %}
<div class="content">
    <h2>募集編集</h2>
    <div class="delete-link-area"><a href="{% url 'overwin:party_recruitment_delete' pk=recruitment.id %}" class="btn btn-secondary delete-link">募集を削除</a></div>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="field-area">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="action-button-area">
            <button name="update" type="submit" class="btn btn-primary" >更新する</button>
            <a href="{% url 'overwin:party_recruitment_detail' pk=recruitment.pk %}" class="btn btn-secondary back-link">募集詳細に戻る</a>
        </div>
    </form>
</div>
{% endblock %}